export const GET_CART_ITEM_REQUEST = "GET_CART_ITEM_REQUEST";
export const GET_CART_ITEM_SUCCESS = "GET_CART_ITEM_SUCCESS";
export const GET_CART_ITEM_FAIL = "GET_CART_ITEM_FAIL";

export const CART_ADD_ITEM_REQUEST = "CART_ADD_ITEM_REQUEST";
export const CART_ADD_ITEM_SUCCESS = "CART_ADD_ITEM_SUCCESS";
export const CART_ADD_ITEM_FAIL = "CART_ADD_ITEM_FAIL";

export const CART_REMOVE_ITEM_REQUEST = "CART_REMOVE_ITEM_REQUEST";
export const CART_REMOVE_ITEM_SUCCESS = "CART_REMOVE_ITEM_SUCCESS";
export const CART_REMOVE_ITEM_FAIL = "CART_REMOVE_ITEM_FAIL";

export const CART_ADD_ADDRESS = "CART_ADD_ADDRESS";
export const CART_REMOVE_ADDRESS = "CART_REMOVE_ADDRESS";

export const CART_PLACE_ORDER_REQUEST = "CART_PLACE_ORDER_REQUEST";
export const CART_PLACE_ORDER_SUCCESS = "CART_PLACE_ORDER_SUCCESS";
export const CART_PLACE_ORDER_FAIL = "CART_PLACE_ORDER_FAIL";

export const EMPTY_CART_REQUEST = "EMPTY_CART_REQUEST";
export const EMPTY_CART_SUCCESS = "EMPTY_CART_SUCCESS";
export const EMPTY_CART_FAIL = "EMPTY_CART_FAIL";
