export const CREATE_GROUP_CART_REQUEST = "CREATE_GROUP_CART_REQUEST";
export const CREATE_GROUP_CART_SUCCESS = "CREATE_GROUP_CART_SUCCESS";
export const CREATE_GROUP_CART_FAIL = "CREATE_GROUP_CART_FAIL";

export const GET_GROUP_CART_REQUEST = "GET_GROUP_CART_REQUEST";
export const GET_GROUP_CART_SUCCESS = "GET_GROUP_CART_SUCCESS";
export const GET_GROUP_CART_FAIL = "GET_GROUP_CART_FAIL";

export const GET_GROUP_CARTS_USER_IS_IN_REQUEST =
  "GET_GROUP_CARTS_USER_IS_IN_REQUEST";
export const GET_GROUP_CARTS_USER_IS_IN_SUCCESS =
  "GET_GROUP_CARTS_USER_IS_IN_SUCCESS";
export const GET_GROUP_CARTS_USER_IS_IN_FAIL =
  "GET_GROUP_CARTS_USER_IS_IN_FAIL";

export const DELETE_GROUP_CART_REQUEST = "DELETE_GROUP_CART_REQUEST";
export const DELETE_GROUP_CART_SUCCESS = "DELETE_GROUP_CART_SUCCESS";
export const DELETE_GROUP_CART_FAIL = "DELETE_GROUP_CART_FAIL";

export const ADD_CART_IN_NEW_CART_STATE = "ADD_CART_IN_NEW_CART_STATE";
export const ADD_PRODUCT_IN_CURRENT_CART = "ADD_PRODUCT_IN_CURRENT_CART";
export const REMOVE_PRODUCT_FROM_CURRENT_CART =
  "REMOVE_PRODUCT_FROM_CURRENT_CART";
export const ADD_USER_IN_CURRENT_CART = "ADD_USER_IN_CURRENT_CART";
export const REMOVE_USER_IN_CURRENT_CART = "REMOVE_USER_IN_CURRENT_CART";

export const CHANGE_GROUP_CART_REQUEST = "CHANGE_GROUP_CART_REQUEST";
export const CHANGE_GROUP_CART_SUCCESS = "CHANGE_GROUP_CART_SUCCESS";
export const CHANGE_GROUP_CART_FAIL = "CHANGE_GROUP_CART_FAIL";
export const EMPTY_PRODUCTS_FROM_NEW_CART = "EMPTY_PRODUCTS_FROM_NEW_CART";
export const EMPTY_USER_FROM_NEW_CART = "EMPTY_USER_FROM_NEW_CART";
