export const LOGGED_USER_CHANGE_REQUEST = "LOGGED_USER_CHANGE_REQUEST";
export const LOGGED_USER_CHANGE_SUCCESS = "LOGGED_USER_CHANGE_SUCCESS";
export const LOGGED_USER_LOGIN_SUCCESS = "LOGGED_USER_LOGIN_SUCCESS";
export const LOGGED_USER_UPDATE_SUCCESS = "LOGGED_USER_UPDATE_SUCCESS";
export const LOGGED_USER_REMOVE_SUCCESS = "LOGGED_USER_REMOVE_SUCCESS";
export const LOGGED_USER_CHANGE_FAIL = "LOGGED_USER_CHANGE_FAIL";

export const LOGGED_USER_LOGOUT = "USER_LOGOUT";

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";

export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";
