export const GET_WISHLIST_REQUEST = "GET_WISHLIST_REQUEST";
export const GET_WISHLIST_SUCCESS = "GET_WISHLIST_SUCCESS";
export const GET_WISHLIST_FAIL = "GET_WISHLIST_FAIL";

export const ADD_WISHLIST_REQUEST = "ADD_WISHLIST_REQUEST";
export const ADD_WISHLIST_SUCCESS = "ADD_WISHLIST_SUCCESS";
export const ADD_WISHLIST_FAIL = "ADD_WISHLIST_FAIL";

export const REMOVE_WISHLIST_REQUEST = "REMOVE_WISHLIST_REQUEST";
export const REMOVE_WISHLIST_SUCCESS = "REMOVE_WISHLIST_SUCCESS";
export const REMOVE_WISHLIST_FAIL = "REMOVE_WISHLIST_FAIL";

export const EMPTY_WISHLIST_REQUEST = "EMPTY_WISHLIST_REQUEST";
export const EMPTY_WISHLIST_SUCCESS = "EMPTY_WISHLIST_SUCCESS";
export const EMPTY_WISHLIST_FAIL = "EMPTY_WISHLIST_FAIL";
